### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by flouthoc** [yorickdewid/CarbonVPN#2]
Can you please provide documentation btw Project looks great :+1: :smiley:

**Comment by yorickdewid** [comment]
I was just writing the readme. I'll make a short _howto_ to get started with the VPN server.

**Comment by yorickdewid** [comment]
The GitBook is not nearly finished, but you can checkout the [repo](https://github.com/yorickdewid/CarbonVPN-doc).  Please let me know if there lacks information or if anything is unclear.

**Comment by flouthoc** [comment]
:+1:
